---
engines:
  duplication:
    enabled: false
    config:
      languages:
      - javascript
        #mass_threshold: 100

  eslint:
    enabled: true
    channel: eslint-3
    checks:
      no-unused-expressions:
        enabled: false

  fixme:
    enabled: true

ratings:
  paths:
  - '**.js'
exclude_paths:
- test/
